java_binary(
  name = "playmaker",
  main_class = "com.github.rockwotj.playmaker.Main",
  srcs = glob(["*.java", "fieldpieces/*.java"]),
  resources = ["//images"],
  visibility = ["//visibility:public"],
  deps = [
      "@maven//:com_google_guava_guava",
  ],
)
