name: Release
on: [push]
jobs:
  Release-MacOS:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build Release
        run: |
          bazel build -c opt @mac_jdk//...
          bazel build -c opt //java/com/github/rockwotj/playmaker:playmaker_deploy.jar
          mkdir -p appdata
          cp bazel-bin/java/com/github/rockwotj/playmaker/playmaker_deploy.jar appdata/playmaker.jar
          cp images/CCLogo.jpg appdata/CCLogo.jpg
          export JAVA_HOME="$PWD/bazel-cchs-playmaker/external/mac_jdk/Contents/Home"
          $JAVA_HOME/bin/jpackage --input appdata --add-modules java.base,java.desktop \
            --main-jar playmaker.jar --main-class com.github.rockwotj.playmaker.Main \
            --mac-package-name Playmaker --name Playmaker --app-version 2.0 --copyright 'Tyler Rockwood 2021' \
            --description 'A football playmaking drawing program' --vendor 'Tyler Rockwood' \
            --dest build-out --icon CCLogo.jpg
          ls build-out
      - name: Publish Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./build-out
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
