# Here's some good jpackage reading material:
# https://www.devdungeon.com/content/use-jpackage-create-native-java-app-installers
# https://docs.oracle.com/en/java/javase/16/docs/specs/man/jpackage.html
name: Release
on: [push]
jobs:
  Release-MacOS:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build Release
        run: |
          bazel build -c opt //java/com/github/rockwotj/playmaker:playmaker_deploy.jar
          mkdir appdata
          cp bazel-bin/java/com/github/rockwotj/playmaker/playmaker_deploy.jar appdata/playmaker.jar
          cp images/logo.jpg appdata/logo.jpg

          bazel build @mac_jdk//:jdk
          mkdir jdkdata
          tar --extract --file=bazel-bin/external/mac_jdk/jdk.tgz --directory=jdkdata
          export JAVA_HOME="$PWD/jdkdata/Contents/Home"
          $JAVA_HOME/bin/jpackage --input appdata --add-modules java.base,java.desktop \
            --main-jar playmaker.jar --main-class com.github.rockwotj.playmaker.Main \
            --mac-package-name Playmaker --name Playmaker --app-version 2.0 --copyright 'Tyler Rockwood 2021' \
            --mac-package-identifier 'com.github.rockwotj.playmaker' \
            --description 'A football playmaking drawing program' --vendor 'Tyler Rockwood' \
            --dest build-out
      - name: Publish Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build-out/Playmaker-2.0.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  Release-Windows:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build Release
        run: |
          bazel build -c opt //java/com/github/rockwotj/playmaker:playmaker_deploy.jar
          mkdir appdata
          cp bazel-bin/java/com/github/rockwotj/playmaker/playmaker_deploy.jar appdata/playmaker.jar
          cp images/logo.jpg appdata/logo.jpg

          bazel build @windows_jdk//:jdk
          mkdir jdkdata
          tar.exe -xf bazel-bin/external/windows_jdk/jdk.tgz -C jdkdata
          $env:JAVA_HOME = "jdkdata/"
          jdkdata/bin/jpackage --input appdata --add-modules java.base,java.desktop `
            --main-jar playmaker.jar --main-class com.github.rockwotj.playmaker.Main `
            --name Playmaker --app-version 2.0 --copyright 'Tyler Rockwood 2021' `
            --description 'A football playmaking drawing program' --vendor 'Tyler Rockwood' `
            --dest build-out --type msi --win-menu --win-menu-group Playmaker --win-shortcut `
            --win-upgrade-uuid 9a011adc-ebea-4bfe-a510-e5b2f85845ea
      - name: Publish Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build-out/Playmaker-2.0.msi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
